INSERT INTO struktur_organisasi (nama, jabatan, posisi, tanggal_input)
VALUES
('Windharti Amelia', 'Human Capital Services Group Head', 'Ketua', CURRENT_DATE),
('Hernasah Suklati', 'Office Administration Department Head', 'Wakil Ketua', CURRENT_DATE),
('Jajang Sahara Nur', 'Employee Services Assistant', 'Sekretaris I / Ahli K3', CURRENT_DATE),
('Yudhi Purwanto', 'Office Administration Specialist', 'Sekretaris II / Ahli K3', CURRENT_DATE),
('Muklis', 'Asset Security Assistant', 'Koordinator Tanggap Darurat / Ahli K3', CURRENT_DATE),
('Tri Subekti', 'Asset Administration Assistant', 'Koordinator Pengamanan Aset K3', CURRENT_DATE),
('Eko Wahyudi', 'Asset Security Assistant', 'Koordinator Security,Teknisi, Cleaning Service / Ahli K3', CURRENT_DATE),
('Wayan Boby Subirman', 'Cash Management Section Head', 'Ahli K3 / Anggota', CURRENT_DATE),
('Abhzal', 'Finance and Accounting Section Head RNT', 'Ahli K3 / Anggota', CURRENT_DATE),
('Tommi Ollismar', 'Human Capital Section Head RNT', 'Ahli K3 / Anggota', CURRENT_DATE),
('Gilang Permana', 'Quality, Health, Safety & Environment Management Specialist', 'Ahli K3 / Anggota', CURRENT_DATE),
('Syahdun Hidayat', 'Corporate Performance Review Specialist', 'Ahli K3 / Anggota', CURRENT_DATE),
('Junaedi', 'Strategic Transformation Specialist', 'Ahli K3 / Anggota', CURRENT_DATE),
('Yudhi Salman Dwi Satya', 'PMO Land & Construction Specialist', 'Ahli K3 / Anggota', CURRENT_DATE),
('Ari Sunarya', 'Junior Auditor', 'Ahli K3 / Anggota', CURRENT_DATE),
('Rico Managam Imanuel Siboro', 'Quality, Health, Safety & Environment Management Assistant', 'Ahli K3 / Anggota', CURRENT_DATE),
('Sarkim', 'Assistant Auditor', 'Ahli K3 / Anggota', CURRENT_DATE),
('Agus Suhanda', 'Procurement Monitoring & Evaluation Senior Officer', 'Ahli K3 / Anggota', CURRENT_DATE),
('Prapto Widodo', 'Quality, Health, Safety & Environment Management Specialist', 'Ahli K3 / Safety Officer', CURRENT_DATE),
('Anggi Gilang Ramadhan', 'Risk Management Specialist', 'Ahli K3 / Safety Officer', CURRENT_DATE),
('Rusi Bin Tatang', 'Industrial Relation Specialist', 'Safety Officer', CURRENT_DATE),
('Siti Halimah', 'Procurement Services Assistant', 'Safety Officer', CURRENT_DATE),
('Nurhasan', 'Employee Services Assistant', 'Ahli K3 / P3K', CURRENT_DATE),
('Yuni Irmawati', 'Office Administration Assistant', 'P3K / Anggota', CURRENT_DATE),
('Erwin Jayanto', 'Archives Management Senior Officer', 'P3K / Anggota', CURRENT_DATE),
('dr. Rani Herdiani', 'Dokter Perusahaan', 'Anggota', CURRENT_DATE),
('Nixon Sitorus', 'Corporate Secretary & Chief Administration Officer', 'Anggota', CURRENT_DATE),
('Devi Lusyana', 'Risk and Quality, Health, Safety & Environment Group Head', 'Anggota', CURRENT_DATE),
('Agung Laksana Pranata', 'Internal Audit Senior Group Head', 'Anggota', CURRENT_DATE),
('Haning Pangastuty', 'Corporate Finance & Investor Relation Senior Group Head', 'Anggota', CURRENT_DATE),
('Dwiwaman Heru Santoso', 'Procurement & Fixed Asset Group Head', 'Anggota', CURRENT_DATE),
('Aprilizayanti Putri', 'Human Capital Development Group Head', 'Anggota', CURRENT_DATE),
('Lisye Octaviana', 'Corporate Communication & Community Development Group Head', 'Anggota', CURRENT_DATE),
('Trias Andriyanto', 'Corporate Planning & Portfolio Management Group Head', 'Anggota', CURRENT_DATE),
('Gandes Aisyaharam', 'Information Technology Group Head', 'Anggota', CURRENT_DATE),
('Syailendra Wisnu Wardhana', 'Legal & Compliance Group Head', 'Anggota', CURRENT_DATE),
('Atika Dara Prahita', 'Operation & Maintenance Management Group Head', 'Anggota', CURRENT_DATE),
('Yuliana', 'Strategic Transformation Group Head', 'Anggota', CURRENT_DATE),
('George I.M.P. Manurung', 'Engineering Planning Group Head', 'Anggota', CURRENT_DATE),
('Aldrin Maulana', 'Business Development Group Head', 'Anggota', CURRENT_DATE),
('Irawati Savitri', 'Jasa Marga Learning Institute Group Head', 'Anggota', CURRENT_DATE),
('Ricky Ricardo Sarael Benyamin', 'Accounting & Tax Group Head', 'Anggota', CURRENT_DATE),
('Tyas Pramoda Wardhani', 'Concession Business Planning Group Head', 'Anggota', CURRENT_DATE),
('Truly Nawangasasi', 'Regional Division Senior General Manager RNT', 'Anggota', CURRENT_DATE),
('Tisa Yuanisa', 'Quality, Health, Safety & Environment System Management Department Head', 'Anggota', CURRENT_DATE),
('Djutiwsanto', 'Employee Services Department Head', 'Anggota', CURRENT_DATE),
('Frred Ferdian', 'HC Information System Department Head', 'Anggota', CURRENT_DATE),
('Agus Budiana', 'Industrial Relation Department Head', 'Anggota', CURRENT_DATE),
('Indra Alamsyah', 'Regulatory Management Department Head', 'Anggota', CURRENT_DATE),
('Mintari Yulianingsih', 'Environmental Department Head', 'Anggota', CURRENT_DATE),
('Vera Nurpujia', 'Revenue Control Department Head', 'Anggota',CURRENT_DATE),
('Tengku Vaisal Rizal', 'Logistic and Inventory Section Head', 'Anggota',CURRENT_DATE),
('Stella Adelin', 'Procurement Services Senior Specialist', 'Anggota',CURRENT_DATE),
('Aditya Rizki Dharmawan', 'Procurement Services Senior Specialist', 'Anggota',CURRENT_DATE),
('Irra Susiyanti', 'Human Capital Development Senior Specialist', 'Anggota',CURRENT_DATE),
('Adinda Kariz Putri', 'Learning Experience Specialist', 'Anggota',CURRENT_DATE),
('Agung Trinanda', 'Toll Road Investment Development Specialist', 'Anggota',CURRENT_DATE),
('Mas’adi', 'Revenue Control Specialist', 'Anggota',CURRENT_DATE),
('Indra Rabuanawal', 'Engineering Area 2 Assistant', 'Anggota',CURRENT_DATE),
('Tatang Supriatna', 'Employee Services Assistant', 'Anggota',CURRENT_DATE),
('Djaswadi', 'IT Support & Services Assistant', 'Anggota',CURRENT_DATE),
('Yudha Rizqi Gumilang', 'Operation Bussines Management Assistant', 'Anggota',CURRENT_DATE),
('Maulana Arief Raditya', 'Quality, Health, Safety & Environment Management Assistant', 'Anggota',CURRENT_DATE),
('Ivana Yeyet R Felle', 'Quality, Health, Safety & Environment Management Assistant', 'Anggota',CURRENT_DATE),
('Krisna Rengga Buana', 'Internet Of Things Project Manager', 'Anggota',CURRENT_DATE),
('Sri Anggoro Prahastono', 'Quality, Health, Safety & Environment Management Assistant', 'Anggota',CURRENT_DATE),
('Muhamad Sihabuddin', 'Toll Collection System Evaluation Assistant', 'Anggota',CURRENT_DATE),
('Asep Supriadi', 'Regulation Assistant', 'Anggota',CURRENT_DATE),
('Sugeng Sutopo', 'Asset Administration Assistant', 'Anggota',CURRENT_DATE),
('Boyke Jaguar', 'Assurance Management Senior Officer', 'Anggota',CURRENT_DATE),
('Adek Firmansyah', 'Learning Experience Senior Officer', 'Anggota',CURRENT_DATE),
('Dedy Sofyan', 'Employee Services Senior Officer', 'Anggota',CURRENT_DATE),
('Yuliani Fajar Sidik', 'Corporate Banking Senior Officer', 'Anggota',CURRENT_DATE),
('Ismail', 'Office Administration Senior Officer', 'Anggota',CURRENT_DATE);



INSERT INTO struktur_organisasi_tanggap (nama_tanggap, jabatan_tanggap, posisi_tanggap, tanggal_input_tanggap)
VALUES
('Muklis', 'Asset Security Assistant', 'Koordinator Tanggap Darurat', CURRENT_DATE),
('Tri Subekti', 'Asset Administration Assistant', 'Koordinator Pengamanan Aset', CURRENT_DATE),
('Eko Wahyudi', 'Asset Security Assistant', 'Koordinator Security, Teknisi, Cleaning Service, Office Boy', CURRENT_DATE),
('Dokter Rani Herdiani', 'Dokter Perusahaan', 'Ketua Medis/P3K', CURRENT_DATE),
('Nurhasan', 'Employee Services Assistant', 'Anggota Medis/P3K', CURRENT_DATE),
('Yuni Irmawati', 'Office Administration Assistant', 'Anggota Medis/P3K', CURRENT_DATE),
('Erwin Jayanto', 'Archives Management Senior Officer', 'Anggota Medis/P3K', CURRENT_DATE),
('Chief Security/Satpam', 'Chief Security', 'Ketua Evakuasi', CURRENT_DATE),
('Supervisor Teknisi 1', 'Supervisor Teknisi', 'Ketua Regu 1 Keberfungsian Alat', CURRENT_DATE),
('Danru Security 1', 'Danru Security', 'Ketua Regu 2 Pengendali Banjir', CURRENT_DATE),
('Supervisor Teknisi 2', 'Supervisor Teknisi', 'Ketua Regu Teknik', CURRENT_DATE),
('Danru Security 2', 'Danru Security', 'Ketua Regu Pengendali Api', CURRENT_DATE),
('Para Ahli K3 Unit Kerja', 'Ahli K3', 'Tim Pengarah Tanggap Darurat', CURRENT_DATE),
('Tim Security', 'Security', 'Anggota Evakuasi', CURRENT_DATE),
('Tim Cleaning Service', 'Cleaning Service', 'Anggota Evakuasi', CURRENT_DATE),
('Tim Office Boy', 'Office Boy', 'Anggota Evakuasi', CURRENT_DATE),
('Tim Gardener', 'Gardener', 'Anggota Evakuasi', CURRENT_DATE),
('Regu 1 Teknisi', 'Teknisi', 'Anggota Regu Teknik/Keberfungsian Alat', CURRENT_DATE),
('Regu 2 Teknisi', 'Teknisi', 'Anggota Regu Teknik/Keberfungsian Alat', CURRENT_DATE),
('Regu 1 Security', 'Security', 'Anggota Regu Pengendali Banjir/Api', CURRENT_DATE),
('Regu 2 Security', 'Security', 'Anggota Regu Pengendali Banjir/Api', CURRENT_DATE);
